lpereira/hardinfo

- hardinfo.desktop.cmake
This pull request adds a _Comment_ section into the desktop file to fix [problems](https://appstream.debian.org/sid/main/issues/hardinfo.html) with AppStream and make HardInfo installable using GNOME Software.
> Fix desktop file

- includes/x86/processor-platform.h
- modules/devices/x86/processor.c
The first commit in this set is simply removing some trailing whitespace from several lines.
The second commit adds handling for the new bugs list from /proc/cpuinfo.
See:
https://github.com/torvalds/linux/commit/80a208bd3948aceddf0429bd9f9b4cd858d526df
https://github.com/torvalds/linux/commit/9b13a93df267af681a66a6a738bf1af10102da7d
> Handle the new "bugs" list from /proc/cpuinfo

- cmake/GNUInstallDirs.cmake
- doc/index.hlp
- modules/benchmark/fbench.c
- modules/benchmark/fftbench.c
- shell/callbacks.c
- shell/report.c
Note: http://www.x86-64.org/documentation/abi.pdf (/cmake/GNUInstallDirs.cmake), http://www.erlenstar.demon.co.uk/unix/faq_3.html#SEC26 (/hardinfo/socket.c), http://www.krugle.org/examples/p-OZYzuisV6gyQIaTu/iwconfig.c (/modules/network/net.c) and http://gentoo-wiki.com/Cpuinfo (/modules/devices/x86/processor.c) don't work.
> Updated URL's to HTTPS

- po/fr.po
There was the message after compiling:
> [100%] Built target network
> /hardinfo/po/fr.po:410: 'msgid' and 'msgstr' entries do not both end with '\n'
> /usr/bin/msgfmt: found 1 fatal error
> po/CMakeFiles/i18n.dir/build.make:57: recipe for target 'i18n' failed
> make[2]: *** [i18n] Error 1
> CMakeFiles/Makefile2:308: recipe for target 'po/CMakeFiles/i18n.dir/all' failed
> make[1]: *** [po/CMakeFiles/i18n.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
@yolateng0, please, be careful.
> Fixed French translation

- .gitignore
Everyone who follows the official build instructions will have a
build/.
Makes `git status` cleaner.
> .gitignore: add build/

- modules/benchmark.c
Fixed compile warning in benchmark.c:
> Scanning dependencies of target benchmark
> [ 48%] Building C object CMakeFiles/benchmark.dir/modules/benchmark.c.o
> /home/maxpayne/hardinfo/modules/benchmark.c: In function ‘get_benchmark_results’:
> /home/maxpayne/hardinfo/modules/benchmark.c:565:37: warning: format ‘%d’ expects argument of type ‘int’, but argument 5 has type ‘long unsigned int’ [-Wformat=]
>      gchar *result = g_strdup_printf("[param]\n"
>                                      ^
> Fixed compile warning in benchmark.c

- modules/computer.c
Fixed compile warning in computer.c:
> [ 70%] Building C object CMakeFiles/computer.dir/modules/computer.c.o
> In file included from /home/maxpayne/hardinfo/modules/computer.c:27:0:
> /home/maxpayne/hardinfo/modules/computer.c: In function ‘callback_os’:
> /home/maxpayne/hardinfo/modules/computer.c:421:30: warning: too many arguments for format [-Wformat-extra-args]
>      return g_strdup_printf(_("[$ShellParam$]\n"
>                               ^
> /home/maxpayne/hardinfo/includes/hardinfo.h:28:30: note: in definition of macro ‘_’
>  #define _(STRING)    gettext(STRING)
>                               ^
> Fixed compile warning in computer.c

- hardinfo/util.c
Fixed compile warning in utils.c:
> [ 37%] Building C object CMakeFiles/hardinfo.dir/hardinfo/util.c.o
> /home/maxpayne/hardinfo/hardinfo/util.c: In function ‘seconds_to_string’:
> /home/maxpayne/hardinfo/hardinfo/util.c:105:34: warning: too many arguments for format [-Wformat-extra-args]
>   return g_strdup_printf(ngettext("%d hour, ", "%d hours, ", hours), hours,
>                                   ^
> /home/maxpayne/hardinfo/hardinfo/util.c:108:37: warning: too many arguments for format [-Wformat-extra-args]
>      return g_strdup_printf(ngettext("%d day, ", "%d days, ", days), days,
>                                      ^
> Fixed compile warning in utils.c

- includes/arm/processor-platform.h
- modules/devices.c
- modules/devices/arm/arm_data.c
- modules/devices/arm/arm_data.h
- modules/devices/arm/processor.c
get_motherboard() will now return something for Raspberry Pi boards.
example:
"Raspberry Pi 3 (Q1 2016) pcb-rev:1.2 soc:BCM2835 mem:1GB mfg-by:Sony"
It can be seen in the GUI by selecting "Computer".
> Get board information for Raspberry Pis

- CMakeLists.txt
- README
I deleted the original branch for #64, so I made a new one with that first patch and another one to set the option on by default as discussed in that conversation.
> cmake: add option to disable sync via libsoup [v2]

- hardinfo/util.c
In Ubuntu, we had a problem building HardInfo on the s390x architecture because the way our build system is set up, it does not allow HardInfo to use the `strend` function if it was inlined. [Here](https://launchpadlibrarian.net/282109653/buildlog_ubuntu-yakkety-s390x.hardinfo_0.5.1-1.4ubuntu1_BUILDING.txt.gz) is the build log from that failure.
Making the changes in this pull request in Ubuntu's packaging made HardInfo buildable on s390x and caused no additional problems.
> Make the strend function accessible

- cmake/GNUInstallDirs.cmake
> cmake: comply with the BSD license by copying the full license text

- modules/computer/os.c
Starting in Debian 9, ldconfig requires root, and so it can't be
used to get the GNU libc version. Try `ldd --version` first. It should
give the same result. (#79)
> Another libc detection fix

- includes/dt_util.h
- modules/devices/devicetree.c
- modules/devices/devicetree/dt_util.c
- test/data/rpi1_raspbian.dts
- test/data/rpi3_arch_arm64.dts
- test/data/rpi3_raspbian.dts
* Added some Device Tree .dts to test/data. Please add more. Use `dtc -I fs /proc/device-tree` or perhaps `dtc -I fs /sys/firmware/devicetree/base` to create.
* Fix bug where every property appeared as byte sequence sometimes.
* Look for Device Tree root in two known locations. Please add more if you find it elsewhere.
* Decode /_ _ overrides _ _ fields
* Started some work decoding clocks and gpios, currently turned off because it is incomplete.
* reg grouping using inherited #address-cells and #size-cells.
> Device Tree related changes

- includes/cpu_util.h
- includes/dt_util.h
- modules/devices/arm/processor.c
- modules/devices/devicetree.c
- modules/devices/devicetree/dt_util.c
- modules/devices/devicetree/pmac_data.c
- modules/devices/ia64/processor.c
- modules/devices/parisc/processor.c
- modules/devices/ppc/processor.c
- modules/devices/riscv/processor.c
- modules/devices/s390/processor.c
- modules/devices/sh/processor.c
* check if device tree was found before add_keys()
* UNKIFNULL(model) before strcmp
* make UNKIFNULL() STRIFNULL() EMPIFNULL() macros more generic
> device tree: fix crash when device tree is not found

- po/salvage.sh
Used as part of https://github.com/lpereira/hardinfo/issues/100
After breaking the labels out of the c-format strings, this tool will help to save the old c-format string translations.
This is not an automated magical tool, it is an ugly hack of a helper for a tedious process. Read the instructions if you want to use it!
> Tool to help save old label translations

- hardinfo/hardinfo.c
Fixes strings not being translated in the CLI.
See: https://github.com/lpereira/hardinfo/issues/105#issuecomment-319002090
> Call setlocale() to clear the default "C" locale for CLI

- hardinfo/hardinfo.c
- includes/hardinfo.h
- po/de.po
- po/es.po
- po/fr.po
- po/hardinfo.pot
- po/ru.po
- shell/callbacks.c
* Makes the copyright line a c-format with the latest year as %d so the line doesn't have to be retranslated each year.
* Restores the Compile-Time Options translations
* Adds a space between columns in the module list table.
And some changes to the about dialog:
* Use a define for copyright latest year, also used by
`hardinfo --version`
* Don't translate Jakub Szypulka
* Add myself to contributors list
And make sure that the entire set of (Days, Hours, Minutes, Seconds) exists for all languages so they are not mixed with English. The Russian form of "second/seconds" are from Google Translate, so feel free to correct them if wrong.
> hardinfo CLI translation fixes

- hardinfo/util.c
- includes/callbacks.h
- includes/hardinfo.h
- includes/uidefs.h
- modules/benchmark.c
- modules/computer/os.c
- modules/network.c
- shell/callbacks.c
- shell/loadgraph.c
- shell/menu.c
- shell/shell.c
- test/ws_scan.sh
Changes based on recent merges and discussions.
* GTK_CHECK_VERSION()-related: shows some code that doesn't need gtk3. If moving up to 2.18 as a requirement (#118), these and all existing conditional code segments for 2.x could be removed. 
* loadgraph gtk2 only, doesn't need conditionals for gtk3.
* Some recent changes to comptuer/os.c caused some compiler warnings.
* Removing tree_view_save_image(), a feature that was "never finished" (https://github.com/lpereira/hardinfo/pull/114#discussion_r129861059)
* The fix to network statistics is just something that was waiting to be in a PR somewhere.
> Various recent stuff

- modules/computer.c
* Break "Not found" out of a c-format
* Tweak GDB regex. Old one would grab only closing paren
> computer.c: tweaks

- CMakeLists.txt
> cmake: fix mistake that broke gui benchmark for gtk2

- benchmark.conf
- includes/arm/processor-platform.h
- includes/devices.h
- includes/dt_util.h
- modules/devices.c
- modules/devices/arm/processor.c
- modules/devices/devicetree.c
- modules/devices/devicetree/dt_util.c
* Benchmark: fix zlib section name, add some ARM results
* ... leads to using the decoded name for ARM instead of the generic one
* ... leads to needing better support from get_processor_name() when there are a mix of different cores
> A trail of related things

- hardinfo/util.c
- hardinfo/vendor.c
- includes/hardinfo.h
- modules/computer/languages.c
- modules/computer/modules.c
- modules/devices/devicetree.c
- modules/devices/inputdevices.c
- modules/devices/pci.c
- modules/devices/usb.c
Continuation of @TotalCaesar659's #129, #130, #131, #132.
* more strings are translatable.
* labels are broken out of c-format strings as described at #100.
* some code cleanup and a few bug fixes along the way.
I did similar work on usb.c, but only tested the __scan_usb_lsusb() method. I can't test __scan_usb_procfs() or __scan_usb_sysfs() because those do not work on any machine I have access to.
> Expanded series based on TotalCaesar659's "Making ... translatable" PR series

- CMakeLists.txt
> cmake: add info.c to gtk3 build/link list

- benchmark.conf
- modules/benchmark.c
- modules/benchmark/bench_results.c
- modules/computer.c
- shell/shell.c
After considering JSON (#142) I decided to just extend the current format, and remain compatible with existing benchmark.conf formats.
* More information can be saved in benchmark.conf, while still being
compatible with older versions.
* Selecting a result gives additional information about the result
and the machine that produced it.
Showing an old result:
Showing a new result:
> Benchmark result details

- modules/computer.c
fix detection for strings and also justify that when gambas are development version git or trunk svn build the versions beetween compiler and interpreter can differs,
> Fix gambas environment detection for gambas X.Y.99 (git)

- modules/network/samba.c
Part of #162: Change samba.c to use g_spawn_command_line_sync() instead of popen() to prevent leaks via stderr.
Prevents this message from appearing:
```
net usershare: cannot open usershare directory /var/lib/samba/usershares. Error No such file or directory
Please ask your system administrator to enable user sharing.
```
The problem is that I have no "usershares", so I didn't test if it is otherwise still working. Will someone who does test that?
> samba.c: popen() leaks via stderr

- modules/computer/boots.c
Part of #162.
boots.c uses `last` to get the list of recent boots. Redirect stderr for popen() to prevent leak via stderr.
The only error would be inability to access /var/log/wtmp.
Also, removes double group header now that info_*() will provide one.
> boots.c: capture stderr to prevent a leak

- hardinfo/dmi_util.c
Fix a crash when there is no DMI available.
> dmi: check for null from dmi_get_str() in dmi_chassis_type_str()

- hardinfo/util.c
Fix for the compilation warning:
```
/home/hardinfo/hardinfo/util.c: In function ‘modules_check_deps’:
/home/hardinfo/hardinfo/util.c:879:13: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
GTK_STOCK_NO,
^
/home/hardinfo/hardinfo/util.c:881:13: warning: ‘GtkStock’ is deprecated [-Wdeprecated-declarations]
GTK_STOCK_OPEN,
^
```
> Fix compilation warning

- shell/callbacks.c
The string is constructed one word at a time, "About", X, "Module"
and it ends up being very strange in languages other than English.
Cutting out the module makes it a little better, and not much is
lost. A module could add "Module" to it's title, and then at
least that string can be translated as a complete unit. 
See https://github.com/lpereira/hardinfo/issues/38#issuecomment-322625707
> Remove the appended "Module" from about module dialog title

- modules/computer/uptime.c
- modules/devices/usb.c
I'm a member of the Pinguem.ru competition on finding errors in open source projects. Warnings, found using PVS-Studio:
hardinfo/modules/devices/usb.c	397	err	V773 The function was exited without releasing the 'temp' pointer. A memory leak is possible.
hardinfo/modules/computer/uptime.c  33      err     V773 The function was exited without releasing the 'ui' pointer. A memory leak is possible.
> Fixed possible memory leak

- modules/computer.c
- modules/computer/display.c
A field exists in struct _DisplayInfo, but it wasn't being
filled or shown.
Perhaps fix: https://github.com/lpereira/hardinfo/issues/181
> Computer/Display: Add X Display Name

- modules/devices/x86/processor.c
- modules/devices/x86/x86_data.c
cpu_insecure = page table isolation is being used to work around a security vulnerability in Intel x86 CPUs.
> Add Intel cpu_insecure bug workaround flag

- shell/report.c
(html version)
Like 96980fbf494d9c453c6b558967c90c55e41abe2d, but the html version
of that function. Fixes https://github.com/lpereira/hardinfo/issues/217
> report.c: don't try to use column values that weren't provided

- hardinfo/cpu_util.c
Package ID can be -1, this wasn't handled.
> cpu_util: bug fix

- hardinfo/cpu_util.c
- includes/cpu_util.h
- includes/x86/processor-platform.h
- modules/devices/arm/processor.c
- modules/devices/x86/processor.c
Show actual clocks where cores or threads share a clock.
Ex: x86 SMT each core has one clock shared by both threads.
Ex: BCM2837 has one clock for all four cores.
> x86,arm: cpu clocks list in package information

- includes/report.h
- shell/report.c
For benchmark results, the current machine will be highlighted in the list by using the shell's select marker.
Text version simply has an asterisk (*) before the highlighted row.
HTML version looks like this now:
> report: highlight "selected" items

- CMakeLists.txt
- hardinfo/usb_util.c
- includes/usb_util.h
- modules/devices.c
- modules/devices/usb.c
A set of functions for getting information for a single USB device,
or a list of all devices.
The only implemented method is using `lsusb`, which is slow. A
method using sysfs would be much better. The existing sysfs and
procfs methods in devices/usb.c do not appear to work, so it would
have to be something new.
devices/usb.c modified to use usb_util, but all the old code is
still there.
Solves #162 for devices/usb.c
Before it was common for `lsusb` to leak the message below once for each device.
`Couldn't open device, some information will be missing`
Fixed a problem with #175.
> usb_util.c [v2]

- shell/shell.c
Hardinfo no longer has a window icon in the taskbar.
Caused by small typo in 1906d3027dc3ad8b9b5533712299d48e265c852c
> shell: fix hardinfo window icon

- hardinfo/hardinfo.c
Solution to #231.
Instead of g_error(), print message to stderr and set a non-zero exit value.
> Remove use of g_error() for reporting user error

- CMakeLists.txt
- hardinfo/gpu_util.c
- hardinfo/pci_util.c
- hardinfo/x_util.c
- includes/computer.h
- includes/devices.h
- includes/gpu_util.h
- includes/pci_util.h
- includes/x_util.h
- modules/computer.c
- modules/computer/display.c
- modules/devices.c
- modules/devices/gpu.c
- modules/devices/pci.c
Working on #225, I've started to enumerate GPU devices. Along the way I wrote new PCI utility functions, and changed Devices/PCI to use them. Added X utility functions and changed Computer/Display to use them.
This series also fixes the issue described at #162 for devices/pci.
> GPU and Display Information

- hardinfo/util.c
- includes/hardinfo.h
- modules/benchmark.c
If you just need the hardware report, this makes it so much faster.
> hardinfo: add cli option to skip benchmarks

- hardinfo/vendor.c
- includes/vendor.h
* Rename struct members to be less ambiguous
* Sort the list by length of match_string so better matches
match first
* Add flag to force case-sensitive matching so that two or
three-letter names don't match names that happen to have
those letters in them
Also, added ASUS and fixes #241.
> vendor.c: try and reduce the likelihood of false matches

- modules/devices/storage.c
This is a hack to address #240. The storage scanner needs work in the future, but this will help for now.
> devices/storage: try `lsscsi -c` if /proc/scsi/scsi is not found

- includes/hardinfo.h
missing <unistd.h> at "hardinfo.h" produces some errors in many environments
> fix for #251 missing <unistd.h> at "hardinfo.h"

- hardinfo/hardinfo.c
- hardinfo/vendor.c
- includes/vendor.h
* Initialize strings to empty in `read_from_vendor_ids()`
* vendor.ids format reader clears all fields at `name`
* Added `name_short`, and `url_support` fields
* `vendor_cleanup()` function that frees `vendor_list`
* `vendor_match()` returns the whole `Vendor` data structure
> vendor.c: add some data fields and cleanup

- .gitmodules
Removes the warning:
```
1@device:~/hardinfo$ git submodule update --init
Submodule 'deps/uber-graph' (https://gitlab.gnome.org/chergert/uber-graph) registered for path 'deps/uber-graph'
Cloning into '/home/1/hardinfo/deps/uber-graph'...
warning: redirecting to https://gitlab.gnome.org/chergert/uber-graph.git/
Submodule path 'deps/uber-graph': checked out 'd31c8014d8cc9f293dfecfcb4bd6a7bf4d61c0be'
```
> Fix for the fix

- po/de.po
- po/es.po
- po/fr.po
- po/hardinfo.pot
- po/ru.po
hardinfo.pot now has 908 strings (+57)
> translation files update

- modules/computer/languages.c
Fixes #280, crash when `locale -va` returns empty .
> computer/languages: fix crash when no other locales installed

- hardinfo/dt_util.c
- includes/dt_util.h
Decode some properties from `operating-points-v2`, see https://www.kernel.org/doc/Documentation/devicetree/bindings/opp/opp.txt.
> device tree: some operating-points-v2 properties

- modules/devices/arm/processor.c
- modules/devices/x86/processor.c
> arm/x86: clocks list empty when cpufreq is not available

- modules/benchmark/bench_results.c
sscanf() was failing on cpu config strings like: `4x 1459.20 MHz + 4x 1113.60 MHz`. Fixed now.
> bench_results: bug fix for cpus with mixed config

- hardinfo/dt_util.c
- hardinfo/gpu_util.c
- includes/dt_util.h
- includes/gpu_util.h
- modules/devices/arm/processor.c
- modules/devices/gpu.c
* opp = "operating-points", frequency scaling information
from device tree that can be used for cpu, gpu, etc.
https://www.kernel.org/doc/Documentation/devicetree/bindings/opp/opp.txt
* adds helper function to get the opp-v1/opp-v2 range of frequencies
for a node, dtr_get_opp_range() in dt_util.c
* adds a freq range in opp-v2 property for a node in dt
* reports a gpu's max clock frequency if avaiable via opp-v1/v2
>  devicetree: get opp-v1/v2 freq range for gpu, if available [v2]

- modules/devices/sensors.c
That was the reason why sensor labels were not loaded from config file. Fixed now.
> devices/sensors: bug fix - read_sensor_labels never gets called

- hardinfo/util.c
- includes/hardinfo.h
- includes/report.h
- includes/shell.h
- modules/benchmark.c
- modules/devices/arm/processor.c
- modules/devices/devicetree.c
- modules/devices/x86/processor.c
- shell/report.c
- shell/shell.c
* Fixes #223
* Used by  Devices/Processors/Package Info
* Used by Devices/Device Tree/Summary
* Can be forced for all items with -w
Somewhat related:
* Report benchmark results are now sorted and limited to the 10 nearest results to avoid clutter.
* A new "shell" report format that is very useful for debugging, is not advertised in --help
> shell/report: allow "moreinfo" details to appear in reports; sort benchmark results in reports

- data/vendor.ids
- hardinfo/dmi_util.c
- hardinfo/gpu_util.c
- hardinfo/vendor.c
- includes/dmi_util.h
- includes/vendor.h
- modules/devices.c
- modules/devices/dmi.c
This reverts a change 2db563687071c099851c59396bdde29a00dba156.
It seems to me that using product version in this way gives
inconsistent values.
The recent benchmark result submitted demonstrates the problem:
`2.0 / X370 SLI PLUS (MS-7A33) (Micro-Star International Co., Ltd.)`
The product version `2.0` is put in front, but without the product
name or product vendor for context, it doesn't really add anything.
The board vendor, which otherwise would be in front, is now in () at
the end.
When the product version is not defined, then the motherboard is
reported as `<board vendor> <board name>`. The only time it is
`<board name> (<board vendor>)` is when product version is defined.
If this change is applied, that same motherboard would be reported
`Micro-Star International Co., Ltd. X370 SLI …
> devices: Remove product-version from string returned by get_motherboard()

- hardinfo/hardinfo.c
- hardinfo/util.c
- includes/hardinfo.h
- modules/devices/printers.c
- modules/devices/resources.c
- modules/network.c
The html_ok param added in 970174b0897d40b804808632784ffa1544d9da93
is misleading. It turns out that it is not HTML,
but Pango Markup that is used by GTK, and a subset of that
happens to also work as HTML4 for the HTML report generation.
This change renames html_ok to markup_ok in ProgramParameters
and adds a comment explaining what common set of tags may be
used.
Also, if report generation happens as a fallback after GUI
initialization failed, then also disable markup, unless report
will be generated as HTML.
Pango markup info at:
https://developer.gnome.org/pango/stable/PangoMarkupFormat.html
> params: html_ok -> markup_ok

- shell/shell.c
Fixes https://github.com/lpereira/hardinfo/issues/304
After 9eaf1a7a96aabc021594bcc6f5fe2ef60da8fb0c, the
whole key part, including the opening and closing '$',
is stored in INFO_TREE_COL_DATA so that the
key_*() functions can be used against it anywhere.
The first '$' no longer needs to be skipped.
> Fix missing icons

- modules/computer.c
- modules/computer/os.c
The Desktop Environment field was missing in current git master. I think it was removed by mistake, because the `detect_desktop_environment` function seems to be working just fine. I have also added function for detecting MATE version.
> Re-added Desktop Environment field and added MATE version detection

- CMakeLists.txt
- hardinfo/udisks2_util.c
- includes/udisks2_util.h
- modules/devices.c
- modules/devices/storage.c
This PR adds initial udisks2 support. Udisks2 is preinstalled on many popular linux distros and can be used for getting additional drive information.
So far this code is using udisks2 for loading additional SCSI drives information (like serial number, size, rotation rate, smart info...) for Devices/Storage, but it can be later expanded for stuff like partitions info, temperature monitoring in Devices/Sensors, ...
> devices/storage: added udisks2 support

- hardinfo/util.c
- includes/hardinfo.h
- modules/benchmark.c
As mentioned in the commit message for 98047b942cd0f6edf4691ed2ba1f3cece8cbe9c7.
> add hardinfo param for maximum number of benchmark results to include

- CMakeLists.txt
- hardinfo/gpu_util.c
- hardinfo/pci_util.c
- hardinfo/x_util.c
- includes/hardinfo.h
- modules/benchmark/bench_results.c
- modules/benchmark/zlib.c
- modules/devices/spd-decode.c
- modules/network.c
For #298:
I: Program is using uninitialized variables. Note the difference between "is used" and "may be used"
I: Program returns random data in a function
----
> Fixes for #298

- .gitmodules
- CMakeLists.txt
- deps/uber-graph/README
- deps/uber-graph/g-ring.c
- deps/uber-graph/g-ring.h
- deps/uber-graph/uber-frame-source.c
- deps/uber-graph/uber-frame-source.h
- deps/uber-graph/uber-graph.c
- deps/uber-graph/uber-graph.h
- deps/uber-graph/uber-heat-map.c
- deps/uber-graph/uber-heat-map.h
- deps/uber-graph/uber-label.c
- deps/uber-graph/uber-label.h
- deps/uber-graph/uber-line-graph.c
- deps/uber-graph/uber-line-graph.h
- deps/uber-graph/uber-range.c
- deps/uber-graph/uber-range.h
- deps/uber-graph/uber-scale.c
- deps/uber-graph/uber-scale.h
- deps/uber-graph/uber-scatter.c
- deps/uber-graph/uber-scatter.h
- deps/uber-graph/uber-timeout-interval.c
- deps/uber-graph/uber-timeout-interval.h
- deps/uber-graph/uber-window.c
- deps/uber-graph/uber-window.h
- deps/uber-graph/uber.h
- shell/loadgraph-uber.c
Includes the hardinfo-required source files directly instead of using a git submodule. The original is unmaintained. Uber-graph is only used with the experimental GTK3 build.
@tsimonq2 : Does this help with https://github.com/lpereira/hardinfo/issues/101#issuecomment-329985085 ?
> Replaces the uber-graph submodule with a local fork

- modules/devices/sensors.c
- Performance improvement: instead of blindly trying to read sensor files 256 times, the sensor file names are determined based on directory listing. Because `g_dir_read_name` do not sort filenames, it is first determined which files exists and then read in for-loop. This also fixes my problems described in issue #312 
- Added support for Current and Power sensors
- Removed unwanted whitespace from sensor labels
> devices/sensors: hwmon improvements

- data/vendor.ids
...from https://github.com/bp0/verbose-spork/blob/master/data/vendor.ids
Includes the two recently added plus some more. 
ansi_color and match_string_exact will just be ignored by hardinfo, which doesn't use them
yet.
> vendor.ids: newer version

- modules/devices.c
- modules/devices/spd-decode.c
This PR adds initial support for decoding DDR4 SPD. It is needed to have ee1004 driver loaded and properly configured.
If you are getting hinote _A current driver has provided only partial DDR4 SPD data_:
- make sure ee1004 driver is loaded
- unload eeprom driver
- Follow these instructions how to instantiate ee1004 devices manually  (https://www.spinics.net/lists/linux-i2c/msg32331.html):
> First you must find out the i2c bus number of your motherboard's SMBus,
> using i2cdetect (i2cdetect is part of the i2c-tools package.) Example:
> ```
> # modprobe i2c-dev
> # i2cdetect -l | grep smbus
> i2c-4	smbus     	SMBus I801 adapter at f040      	SMBus adapter
> ```
> So the SMBus is i2c-4. Then you must find the I2C addresses of the
> SPD EEPROMs:
> ```
> # i2cdetect -y 4 0x50 0x57
>      0  1 …
```
> devices/spd: Add initial DDR4 SPD support

- modules/devices/sensors.c
1. commit - Formulas in a compute statement in sensors.conf are separated with comma. Current implementation worked only when there was space before comma. This commit should fix that.
2. commit - Driver name was so far used as:
- part of label in "Sensor" column,
- part of the moreinfo key,
- label which was used to search actual hwmon device in sensors.conf (by "chip" statement). This was the issue, because according to the sensors.conf man page: chip statement contains "chip type"; which seems to be whatever is written in "name" file (according to sensors app output). Driver name and device name ("name" file) are not always the same. That's why I replaced driver name with device name.
> devices/sensors - Sensors.conf parsing fixes

- includes/devices.h
- modules/devices.c
- modules/devices/dmi.c
There's nothing preventing this from running on non-x86. If it is not available it will just say so, like PCI.
> Allow DMI on non-x86

- CMakeLists.txt
- includes/computer.h
- includes/devices.h
- modules/benchmark.c
- modules/benchmark/bench_results.c
- modules/computer.c
- modules/computer/memory_usage.c
- modules/devices.c
As discussed in https://github.com/lpereira/hardinfo/issues/345.
Everything seems to be working, except there is now a message at startup:
> Module "Computer" depends on module "devices.so"
Didn't it always? I'm not sure what I changed that causes this message. This also blocks benchmarks from working, because the spawned process dies with this message.
Maybe @lpereira could fix that?
> move devices/memory to computer/memory usage

- modules/devices.c
As @ocerman mentioned recently in #243. 
`/sys/class/nvme` could be used, but is there any recent system that doesn't include udisks2 that also might have the relatively new nvme?
edit: note a slight conflict with #355 that should be easy to resolve.
> Not(e) for missing nvme info without udisks2

- CMakeLists.txt
- modules/devices.c
- modules/devices/dmi_memory.c
- modules/devices/x86/processor.c
As discussed #345. Following #354.
SPD is still preferable because Hardinfo doesn't need to run as root, only the user has to add the required module. I would still like to merge Memory DMI and Memory SPD in the future, if a way can be found to match the information from DMI and SPD and create an abstract Memory Slot/Module structure to display.
> DMI socket/module information moved from Processor to Memory DMI

- modules/devices/dmi_memory.c
dmidecode returns `<BAD INDEX>` when it doesn't recognize the manufacturer code. Pango tries to use it as a tag and causes an error.
> devices/dmi_memory.c: fix for <BAD INDEX> from dmidecode

- CMakeLists.txt
- includes/hardinfo.h
- modules/devices/dmi_memory.c
ViewType=1 version:
Notes:
* add -std=c99 for dmi_memory.c to use a unicode arrow
* -std=c99 is picky about inline functions
> devices/dmi_memory.c: shell viewtype=1 version, other tweaks

- modules/devices/spd-decode.c
Adding ! in front of the key causes the "moreinfo" details to be included in a `hardinfo -r` report.
> devices/spd-decode.c: show spd details in reports

- data/benchmark.conf
- modules/benchmark/zlib.c
The new version uses a fixed time (7s) and the results are much
more consistent than the previous version.
A couple results for the new version, one "low" and one "high",
replace the old results, which were quite strange.
This will probably conflict with #299.
> benchmark/zlib: new version of zlib benchmark

- .gitignore
I have build-gtk3/ and build-dbg/ that are annoying me
in the git status.
...if you don't mind.
> add build-* dirs to .gitignore

- hardinfo/udisks2_util.c
- includes/udisks2_util.h
- modules/devices/storage.c
- shell/callbacks.c
The media labels were changed to more familiar style.
For example: "optical_dvd_plus_rw_dl" was changed "DVD+RW DL".
Also I have added myself to contributors list in about dialog.
> Devices/storage: Better storage media labels

- modules/devices/storage.c
Fixes #394
`media_comp` doesn't always get set, so
needs to be set to null after free to be
re-used.
> devices/storage: fix crash on double free

- hardinfo/dmi_util.c
- includes/dmi_util.h
- modules/devices/dmi_memory.c
- modules/devices/spd-decode.c
- modules/devices/spd-vendors.c
- modules/devices/x86/processor.c
If a locator of array > socket is not unique, then use array > bank > socket in the list.
As suggested in #386.
How does this work for you @ocerman ?
> Memory devices: show bank in locator if needed 

- includes/shell.h
- shell/shell.c
See: #391
I split this out of #393 because it isn't really related to the struct Info stuff, it just fixes a bug in the existing icon handling.
> shell: fix icons with flags [v3]

- hardinfo/udisks2_util.c
- includes/udisks2_util.h
- modules/devices/storage.c
When using udisks2 >= 2.7.2, partitions list now shows partition label, size and filesystem
> devices/storage - added more partitions info

- shell/report.c
Fix the warning:
report.c: In function ‘make_icon_css’:
shell/report.c:103:9: warning: ‘return’ with no value, in function returning non-void [-Wreturn-type]
Failure of the sanity test at the beginning of "make_icon_css" will result in returning
of a random value instead of a gchar*.
With this patch we return a gchar* to an empty string instead.
Signed-off-by: Juro Bystricky <juro.bystricky@intel.com>
> shell/report.c: fix "return with no value"

- data/benchmark.conf
- includes/benchmark.h
- modules/benchmark.c
- modules/benchmark/bench_results.c
- modules/benchmark/zlib.c
* add an integer revision field
* add an extra information string field
* zlib benchmark: new revision[1] is 2, so that old results are obviously old,
and now the zlib version string will be stored in extra information.
[1] as of 6a8e19a14305079b03e45eeb0580a45104f300dd
> benchmark: add extra fields to result for revision and information

- hardinfo/info.c
- includes/info.h
I started this a while ago (2017, I think, see #180 and #197) when I was trying to make a new shell that only operated using struct Info. The info_unflatten() function makes an Info struct from the old shell key/value file format string. Trying to do it exposed many problems with the Info struct at the time and I gave up trying to solve them all, and gave up on the new shell.
I've updated the function for more recent changes to the Info struct and shell, but there are still a few problems. For example, group.name always leaks from an unflatten()-ed Info.
This function seems very useful for the original purpose: shell could be rewritten to be Info-only without changing everything else. I've also found it can be useful for debugging.
> struct info unflatten [v2]

- shell/shell.c
label is supposed to end at the '#'.
> shell.c: small fix for label

- modules/devices/devicetree.c
- modules/devices/devicetree/rpi_data.c
- modules/devices/dmi_memory.c
Using a lookup table, get the physical memory size and type for known Raspberry Pi boards. This can be used in Computer Summary > Memory as with DMI or SPD sourced information.
> Raspberry Pi memory types

- hardinfo/usb_util.c
- hardinfo/util.c
- includes/hardinfo.h
- includes/usb_util.h
- modules/devices/usb.c
This PR adds sysfs information about USB devices.
This brings additional information (speed, used driver, interface label, reported manufacturer and device name) and also sysfs can be used as a fallback when lsusb is not available.
This PR also contains workaround when same USB interface is parsed multiple times from lsusb output.
> Improved USB devices

- CMakeLists.txt
- data/vendor.ids
- deps/sysobj_early/data/sdcard.ids
- deps/sysobj_early/gui/uri_handler.c
- deps/sysobj_early/gui/uri_handler.h
- deps/sysobj_early/include/auto_free.h
- deps/sysobj_early/include/gg_slist.h
- deps/sysobj_early/include/strstr_word.h
- deps/sysobj_early/include/util_ids.h
- deps/sysobj_early/src/auto_free.c
- deps/sysobj_early/src/gg_slist.c
- deps/sysobj_early/src/strstr_word.c
- deps/sysobj_early/src/util_ids.c
- hardinfo/hardinfo.c
- hardinfo/udisks2_util.c
- hardinfo/util.c
- hardinfo/vendor.c
- includes/hardinfo.h
- includes/udisks2_util.h
- includes/vendor.h
- shell/shell.c
* more fields in Vendor struct.
* match_case -> match_rule and new match rule "exact". match_rule
remains compatible with match_case for old conf format.
* matches must be "whole word" matches so "Harmony" no longer hits
for "ARM".
* Parts outside of () are checked first, so "Foo (formerly Barly)"
matches Foo before Barly, even though Barly is longer and would
otherwise match first.
* vendor_list type (a blessed GSList*) and helper functions to manage
it.
> vendor.ids update and vendor.{h,c} improvements from sysobj version

- CMakeLists.txt
- deps/sysobj_early/include/appf.h
- deps/sysobj_early/include/nice_name.h
- deps/sysobj_early/include/util_sysobj.h
- deps/sysobj_early/src/appf.c
- deps/sysobj_early/src/nice_name.c
- deps/sysobj_early/src/util_sysobj.c
- hardinfo/dt_util.c
- hardinfo/gpu_util.c
- hardinfo/info.c
- hardinfo/vendor.c
- includes/dt_util.h
- modules/computer/ubuntu_flavors.c
- modules/devices/devicetree.c
- modules/devices/dmi_memory.c
- modules/devices/x86/processor.c
x86 CPU:
* Remove (R), (TM), etc
* AMD: remove redundant "X2 Dual Core", "X4 Quad Core", etc
* Move vendor to front if not already
* Remove speed, as the actual speed is usually right next to it
* Remove "CPU", "APU", "Processor" to shorten
* Compress space
Intel GPU:
* Remove (R)
* Abbreviate "Generation": "Gen"
* Remove "Processor", "Controller", and "Device" to shorten
* Compress space
Some examples:
x86 CPU:
```
'AMD Turion(tm) 64 Mobile Technology ML-32' ---> 'AMD Turion 64 Mobile ML-32'
'Cyrix MediaGXtm MMXtm Enhanced' ---> 'Cyrix MediaGX MMX Enhanced'
'Transmeta(tm) Crusoe(tm) Processor TM5800' ---> 'Transmeta Crusoe TM5800'
'VIA Nano X2 L4350 @ 1.6+ GHz' ---> 'VIA Nano X2 L4350'
'AMD Athlon(tm) 64 X2 Dual-Core Processor TK-53' ---> 'AMD Athlon 64 X2 TK-53'
'Embedded AMD …
```
> name cleanup for x86 model strings and intel pci device strings

- CMakeLists.txt
- deps/sysobj_early/data/usb.ids
- hardinfo/usb_util.c
- includes/usb_util.h
- modules/devices/usb.c
This PR:
- adds usb.ids parsing (from @bp0 sysobj), so now it is possible to get all usb info without lsusb.
- added more properties like serial number
- because lsusb is slower than parsing stuff from sysfs, sysfs method is now used by default (lsusb is called only when sysfs method fails).
> usb: use sysfs info by default

- includes/hardinfo.h
- modules/benchmark/benches.c
- modules/devices.c
- shell/report.c
- shell/shell.c
* fix key_is_highlighted() and key_wants_details() so that they
don't look for flags in the label.
* fix -r -f text, g_hash-related warnings from icon cache
* add MODULE_FLAG_HIDE flag to hide module entries instead of
using the '#' at the beginning of string hack, which didn't
work everywhere, and screwed up translated strings.
* hide GPU Drawing benchmark, at least for now. 
- doesn't work in GTK3 version
- no results with which to compare
- varies wildly, but the details that affect it aren't stored in the bench results
- See: https://github.com/lpereira/hardinfo/issues/329
> various: entry hide flag, fix text format report, fix key_*() funcs

- includes/benchmark.h
- modules/benchmark/bench_results.c
- modules/benchmark/benches.c
- modules/benchmark/sysbench.c
- test/just_bench.sh
* Use a larger sample size for sysbench 1.0+ and 64-bit
* Store pointer size with bench results
* Re-enable single thread memory benchmark
Use a larger sample size where available. The small size was
chosen because the 32-bit ARM sysbench 0.4x in raspbian
can't do more than about ~4G, but the problem is that much more
powerful machines burn through that very quickly. The result is
in MiB/s so it should still be comparable, but the results should
be more stable.
Noticed with Ryzen that multi-thread varies significantly based on
what threads are used, but benchmark doesn't really have control
over that.
> sysbench memory tweaks

- modules/devices/x86/processor.c
Removes warning `Warning: truncated a line (probably flags list) longer than 896 bytes while reading /proc/cpuinfo.`
> x86/processor: bigger buffer for cpuinfo

- deps/sysobj_early/src/nice_name.c
```
'AMD E2-1800 APU with Radeon(tm) HD Graphics' ---> 'AMD E2-1800'
'AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G' ---> 'AMD FX-9800P'
'AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx' ---> 'AMD Ryzen 5 3500U'
```
> nice_name: option to remove "with Radeon" from AMD CPU names

- CMakeLists.txt
- hardinfo/hinote_util.c
- includes/hardinfo.h
- modules/computer.c
- modules/devices/dmi_memory.c
* The check/bullet style for requirements used in Memory Devices can now be used anywhere.
* Used to show requirements for Computer/Display; needs `xrandr` and `glxinfo` or information will be missing. 
* Could be used for others in #243.
Ex: when `xrandr` is available, but `glxinfo` is not:
Style from Memory Devices:
> computer/display: add hinotes for wanted extern utils when missing

- modules/devices/dmi_memory.c
ex: "16 GiB DDR4 SDRAM", when type is known,
or just "16 GiB RAM" when it isn't. (formerly "16 GiB (Unknown)")
> memory devices: use "RAM" for unknown ram type instead of (Unknown)

- CMakeLists.txt
- deps/sysobj_early/data/vendor.ids
- deps/sysobj_early/include/format_early.h
- deps/sysobj_early/src/format_early.c
- hardinfo/info.c
- hardinfo/usb_util.c
- hardinfo/util.c
- includes/hardinfo.h
- includes/info.h
- includes/shell.h
- includes/usb_util.h
- modules/computer.c
- modules/devices/dmi.c
- modules/devices/dmi_memory.c
- modules/devices/firmware.c
- modules/devices/gpu.c
- modules/devices/monitors.c
- modules/devices/pci.c
- modules/devices/printers.c
- modules/devices/storage.c
- modules/devices/usb.c
- modules/devices/x86/processor.c
- shell/report.c
- shell/shell.c
As I said in #493, I think it's better to have the vendor values be the actual data from the hardware or lookup, and the vendor.c match data along side it instead of making a link.
Reasons:
* The actual value is interesting by itself
* There's usually more info available for a vendor than one link
* There might be a mismatch
So instead of doing the vendor lookup ourselves, we can just mark the value as a (possible) vendor
value and then it will be looked up by the shell, and a little info box will be added below it for any match.
To mark the field value as a possible vendor string:
* In the old shell conf style use the flag `^`.
* struct Info style use `(struct InfoField).value_has_vendor`.
* shell function: `key_value_has_vendor_string()` to check for the flag
I've converted these: dmi, …
> Vendor Info and colored vendor tags

- hardinfo/info.c
- hardinfo/pci_util.c
- hardinfo/udisks2_util.c
- includes/info.h
- includes/pci_util.h
- includes/udisks2_util.h
- modules/computer.c
- modules/devices.c
- modules/devices/storage.c
Shows the PCIe vendor/device and link information for NVMe storage.
Updated screengrab with @ocerman's changes:
> Show NVMe controller information in Storage

- hardinfo/pci_util.c
- modules/devices/pci.c
The lspci-using code is still there as fallback. Happy new year.
> pci: get list from sysfs without using lscpi/pciutils

- hardinfo/pci_util.c
Data was missing for nvme controller location
> pci_util: provide .slot_str in pci_get_device_sysfs()

- CMakeLists.txt
- deps/sysobj_early/data/pci.ids.min
- hardinfo/pci_util.c
- includes/pci_util.h
- modules/devices.c
Noticed that the RPi4 has a PCIe bus, but pci.ids is not included with
the standard Raspbian image, so everything is "(Unknown)."
Now there will be some basic information about what the device is, and
a note about installing pci.ids for more information.
> pci: include a minimum pci.ids with classes, note when pci.ids is missing

- CMakeLists.txt
- hardinfo/gg_strescape.c
- hardinfo/info.c
- includes/hardinfo.h
- includes/info.h
- includes/shell.h
- modules/benchmark.c
- shell/shell.c
Adds a new flag `@` to mark the label portion of the key as escaped with `key_label_escape()`. 
`key_get_components()` will automatically un-escape the label part when used.
`key_label_escape()` is just an alias for `gg_strescape()`, a modified version of glib's `g_strescape()` that allows specifying extra characters to escape, in our case "$#=" which have special meaning in the conf file format or in hardinfo. `g_strcompress()` is used as normal to un-escape it. Of course, the escape could be done manually: `=` is `\075`, for example.
Fixes #509.
Still needs some testing, there are a couple TODO:s added, so the LGTM bot will need to comment on every little change....
> [Needs testing] New flag/funcs for escaping label part in shell keys

- deps/sysobj_early/data/vendor.ids
- modules/devices/dmi_memory.c
Fixes #536. Although, this is the only example I have of a dmidecode memory device that is not RAM, so I don't know how universal it is.
> Don't count ROM as RAM in Memory Devices/Arrays

- modules/devices/riscv/riscv_data.c
There is a small typo in modules/devices/riscv/riscv_data.c.
Should read `insensitive` rather than `insensitve`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, insensitve -> insensitive

- modules/devices/sensors.c
Tried to compile on Fedora 33 and ran into the issue that sensors.h could not be found. It turned out that HAS_LIBSENSORS was correctly defined as 0 but since it was defined, the library was expected to be present.
Changed it according to similar occurrences in the project to first check if the variable is defined and then the value.
> Added value check for HAS_LIBSENSORS 

- modules/devices/dmi.c
This PR fixes following issues when the DMI is not availble:
- the 'DMI is not available' message is now properly displayed
- errors in stderr are no longer printed
> devices/dmi: Fixed DMI display when DMI is not available

- modules/devices/dmi_memory.c
- modules/devices/spd-decode.c
- The first commit fixes module size for DDR2 RAM
- The second commit adds more DDR2 SPD information: voltage, module type and timings for alternative speeds
- The third commit adds ignore command for DMI memory type for some placeholder strings (found on ASUS motherboard /w socket 775)
> devices/memory - Improved DDR2

- includes/loongarch64/processor-platform.h
- modules/devices/loongarch64/processor.c
Update ```loongarch``` architecture processor information
The previous ```LoongArch``` support added in commit 56e590d was based on the kernel behavior before the official upstream merge. Stable cpuinfo: https://git.kernel.org/torvalds/c/7153c3c
> Update loongarch architecture processor information
