includes/x86/processor-platform.h, modules/devices/x86/processor.c
Like the Bugs list, there is a now a list for Power Management features. The first patch adds handling for that feature list.
The second patch is just an additional code comment for a "bug."
The third patch simply reorders the feature lists so that the very long Capabilities list is last.
=> Power Management flags list

po/fr.po
hello,
"Great! Please open a pull request, I'll take a look."
it is !
yolateng0
=> .po fr_FR hardinfo

modules/devices/x86/processor.c
Add some more bug "feature" flags from old kernels to the bug
workaround list generated if no such list was available in
/proc/cpuinfo.
Also, fixes a crash if the first bug is not fdiv.
=> More "feature" flags to bug workarounds

includes/arm/processor-platform.h, includes/x86/processor-platform.h, modules/devices/arm/processor.c
Also, fix a code comment in x86.
=> ARM socket/core and more cpufreq information

modules/devices/arm/processor.c, modules/devices/x86/processor.c
Hide Frequency Scaling section instead of showing zeros.
As requested in #78.
=> arm,x86: Don't show frequency scaling information if it isn't available

includes/ppc/processor-platform.h, modules/devices/ppc/processor.c
Based on the recent ARM work.
* Shows multiple processors, like x86 and ARM
* topology: physical package and core ids
* cpufreq: min/max/cur frequency and driver info
Tested against /proc/cpuinfos from a PowerMac G5 and the
Talos POWER8 workstation. Not tested on actual hardware.
=> PPC: Information improvements

po/HOWTO.txt, po/de.po, po/es.po, po/fr.po, po/hardinfo.pot, po/ru.po
Please, merge before anyone does more translating work.
=> Files that couldn't be merged in #92

test/ws_scan.sh
=> Scanner for updating issue #102

shell/shell.c
=> Reset sort order on set_view_type()

modules/computer/memory.c, modules/devices/devicetree.c, modules/devices/devicetree/pmac_data.c, modules/devices/devicetree/rpi_data.c
Also fixes an old bug in computer/memory.c that caused warnings at run time.
=> Add Power Mac data from cpuinfo and device tree to summary

hardinfo.desktop.cmake
=> Add keywords to hardinfo.desktop.cmake

shell/report.c, shell/syncmanager.c
Missed it before because it is disabled by default. Plus, a couple other minor things.
=> GTK3 changes for syncmanager.c

modules/computer.c
Added Gambas compiler,runtime and IDE to development, gambas has a runtime, a compiler and a complete ide, all can be used separatelly but IDE depends on compiler, and compiler depends on runtime: #144 
Gambas its the Visual development most easyle for Linux, theres no languaje similar to Visual Basic but with the power and concepts of Java in Linux.. a hole covered b gambas...
=> Feat: Add Gambas compiler,runtime and IDE to development

po/es.po
Updates remaining translations for Spanish, so collaborate with #105, made into groups of commits
NOTE: this pull remaing only affect the es.po files, **all the pull request must made in realted scope**
=> Spanish updates translations

modules/devices/dmi.c
Recent change to DMI causes it to fail when `/sys/class/dmi/id/product_family` is not available, which is not uncommon.
=> dmi: fail if only never succeeded in dmi_get_info_sys()

hardinfo/info.c, modules/computer.c
As reported here: https://github.com/lpereira/hardinfo/issues/38#issuecomment-322467550
=> Remove duplicate group headers in computer summary

modules/computer/display.c, modules/devices/devmemory.c, shell/callbacks.c
Fixes for https://github.com/lpereira/hardinfo/issues/38#issuecomment-322357433.
=> More translatable strings

modules/computer.c
Perhaps it will help with #154.
=> Add another virtualbox test; make virt strings translatable

modules/benchmark/bench_results.c
Also, a couple other minor tweaks.
=> bench results: Show Unknown instead of 0 KiB for old results

modules/devices/x86/processor.c
* Bug fix: Some flags are just an index, for example power
management might have "[13] [14]" as flags. This looks like
a new section to hardinfo shell and it truncates the CPU
information there.
* Show the Socket:Core and thread in the processor list, for
x86 only right now. In the future, the idea is to show only
one line for each core, and list the threads on that core,
where currently, there is one line for each thread.
=> x86: cpu flags fix; show socket:core and thread in proc list

benchmark.conf, hardinfo/hardinfo.c, hardinfo/util.c, includes/benchmark.h, includes/hardinfo.h, modules/benchmark.c, modules/benchmark/bench_results.c, modules/benchmark/benches.c, modules/benchmark/blowfish.c, modules/benchmark/cryptohash.c, modules/benchmark/drawing.c, modules/benchmark/fft.c, modules/benchmark/fib.c, modules/benchmark/nqueens.c, modules/benchmark/raytrace.c, modules/benchmark/zlib.c
This is PR #212 without the two new benchmarks added.
=> Benchmark fixes only

modules/benchmark.c
Can get this with `-g conf` now.
=> benchmark.c: remove debug printf()

modules/devices/usb.c
=> devices/usb: remove unnecessary incrementation

hardinfo/vendor.c, includes/vendor.h, modules/devices/gpu.c, modules/devices/pci.c
=> Fix vendor sort, re-enable vendor functions for pci and gpu

modules/computer/languages.c
Part of #162.
I don't know if this would ever leak.
=> languages.c: popen() -> g_spawn_command_line_sync(), capture stderr

data/benchmark.conf
Please merge. Thanks.
Resolves #273
=> Add Ryzen 5 1600 benchmark results

modules/computer.c
Firefly ROC-RK3328-CC and Firefly ROC-RK3399-PC
=> computer.c: catch more SBCs

po/zh_CN.po
=> add zh_CN.po

hardinfo/gpu_util.c, includes/gpu_util.h, modules/devices/gpu.c
Will now look for any .../gpu and .../gpu@<address> instead of looking only at /soc/gpu.
=> dt gpu: find gpu in the device tree

modules/devices/arm/processor.c
Add a couple common sbc soc vendors.
=> arm: soc vendors amlogic and allwinner

data/vendor.ids, hardinfo/dmi_util.c, includes/dmi_util.h, modules/devices/x86/processor.c
Requires running as root, but adds CPU and Memory socket information from DMI.
Here's a screengrab:
=> DMI Sockets information

modules/devices/sensors.c
If sensor label is not defined in config file, it will be loaded from sysfs
=> devices/sensors - hwmon: Added support for sysfs labels

modules/computer/os.c
Seems like there was small mistake in for loop. Should be fixed now.
=> computer/os: fix parse_os_release

modules/devices/sensors.c
The hash table is currently using keys based on sensor name, like "temp1". This causes problems when they are multiple drivers that share same sensor name. So for example if a label is defined in config file for driverA/temp1, the same label is incorrectly used also for driverB/temp1.
This PR adds driver name to the hash key and that fixes mentioned issue.
=> devices/sensors - hwmon: FIX - Ambiguous hash table keys

hardinfo/udisks2_util.c, includes/udisks2_util.h, modules/devices/storage.c
This PR adds Power Managment, Advanced Power Management, Automatic Acoustic Management, Partition table type and Partitions list
=> devices/storage - udisks2: added pm, apm, aam, part. table and partitions list

modules/devices/spd-decode.c
First commit is format cleanup, second commit is the fix.
=> Fix: Memory SPD has the wrong viewtype if there is an error

hardinfo/gpu_util.c, includes/gpu_util.h, modules/devices/gpu.c
Show the min/max core and memory frequency for AMD GPUs with amdgpu driver
=> devices/gpu: amdgpu - core and memory clocks

modules/devices/spd-decode.c
- Added Voltage
- Added initial XMP 2.0 support
- Fixed DDR4 Manufacturer
=> devices/spd: Improved DDR4 SPD support

modules/devices/spd-decode.c
Commit 1: Added manufacturing date
Commit 2: Added DRAM Manufacturer
Commit 3: FIX - Partial data is evaluated every refresh (not only on first time)
=> devices/spd: More DDR4 improvements

modules/devices/spd-decode.c
This PR implements @bp0's idea (in #341) to fallback to another driver when no devices are found. (So when no ee1004 devices are found, hardinfo will fallback to eeprom driver)
This also fixes freeing uninitialized pointer problem in decode_dimms function (@bp0 reported that in #341).
=> devices/spd-decode: Fallback to another driver when no devices are found

modules/devices/spd-decode.c
This should fix #345
* Fixed DDR3 Module size
* Added DDR3 Module Manufacturer
* Fixed DDR3 tCL
=> devices/spd: Fixes and improvements for DDR3

modules/devices.c
=> devices.c: fix field update for sensors

modules/devices/dmi_memory.c
Eventually the list might be used to match the DMI and SPD data and unify the memory information.
=> dmi_memory.c: rewrite function dmi_mem_socket_info()

modules/devices/dmi_memory.c
=> devices/dmi_memory.c: array as struct, show installed/max for size/modules

CMakeLists.txt, includes/devices.h, modules/devices.c, modules/devices/dmi_memory.c, modules/devices/spd-decode2.c
Combines the information from DMI and SPD into a single Memory Devices section.
This is just a squash of #369, see there for more information.
=> Combine Memory DMI and Memory SPD into "Memory Devices"

data/benchmark.conf
There is a low and "high" result, now a medium.
=> add medium zlib bench result

modules/devices/dmi_memory.c, modules/devices/spd-decode.c
=>  Memory Devices: Fix DMI to SPD matching 

modules/devices/storage.c
There was small mistake in my last PR: it could display incorrect current media in some cases. This is the fix.
=> devices/storage: current media fix

hardinfo/info.c, includes/info.h, modules/computer.c
=> struct info: add moreinfo() tag and flags support, field sort

modules/computer/display.c
=> computer/display: handle unknown session type

hardinfo/util.c, includes/hardinfo.h, shell/callbacks.c, shell/report.c
See: https://github.com/lpereira/hardinfo/pull/417#discussion_r308512774
=> Remove old open_url() in favor or uri_open()

hardinfo/gg_key_file_parse_string_as_value.c, hardinfo/info.c, shell/shell.c
Also fixed a FIXME: use g_key_file_get_string_list().
=> shell/info: allow newlines in values

CMakeLists.txt, deps/sysobj_early/data/arm.ids, deps/sysobj_early/data/sdcard.ids, deps/sysobj_early/data/vendor.ids, deps/sysobj_early/include/auto_free.h, deps/sysobj_early/src/auto_free.c, hardinfo/udisks2_util.c, modules/devices/arm/arm_data.c, modules/devices/arm/arm_data.h, modules/devices/arm/processor.c
vendor.ids coverage:
Linux/os_release: 8 / 17
JEDEC Mfgr: 72 / 995
PCI Vendor: 187 / 2174
USB Vendor: 252 / 3004
Device Tree Vendor: 12 / 12
ARM Mfgr: 12 / 12
SD Card Vendor/Mfgr: 19 / 27
SDIO Vendor: 19 / 19
=> update sdcard.ids, vendor.ids; use arm.ids

hardinfo/vendor.c
Alternative to https://github.com/lpereira/hardinfo/pull/418
=> Add GTK_CHECK_VERSION(2, 18, 0) for links in label

modules/devices/inputdevices.c
=> input devices fix vendor links

po/pt_BR.po
Obs: This file is not all revised
=> Add portuguese language  translation

includes/hardinfo.h, shell/report.c
=>  report: show icons for module entry in HTML report 

hardinfo/vendor.c
Some vendors, like those defunct, may not have url, but may have
a wikipedia article. Use wikipedia in the link in those cases.
Also, Wikipedia offers more information than the vendor's site
in most cases, and has the vendor's url right there in the sidebar
to click, if desired. I think using wikipedia for links is
prefereable, but this could be turned off by setting
link_wikipedia to FALSE.
=> vendor: vendor_get_link_from_vendor() use wikipedia in some cases

modules/devices/firmware.c
Fixes https://github.com/lpereira/hardinfo/issues/450
=> firmware: fix duplicate guids

data/benchmark.conf
https://github.com/lpereira/hardinfo/issues/458#issuecomment-526359828
=> add bench result

hardinfo/udisks2_util.c, includes/udisks2_util.h, modules/devices/storage.c
=> devices/storage: Added normalized values of reported S.M.A.R.T. attributes

deps/sysobj_early/src/auto_free.c, hardinfo/info.c, includes/report.h, shell/report.c
=> Fixes for newlines in values

po/pt_BR.po
I remove all conflicts files and make a new clean file to translate to portuguese language.
=> Update pt_BR 04092019

README.md
I fixed up some of the grammar and spelling in the README to increase the readability. If I messed anything up, just tell me.
=> Fix up README grammar and spelling

deps/sysobj_early/include/util_ids.h, deps/sysobj_early/src/util_ids.c
Fixes https://github.com/lpereira/hardinfo/issues/476
=> util_ids: fix, update

modules/devices/dmi_memory.c
if no eeprom for SPD, and no root for DMI, try online block count x block size.
=> memory devices: sum online blocks as fallback physical memory count

modules/computer/modules.c
This PR adds kernel module icons based on module paths.
=> Added module icons

modules/devices/arm/processor.c
=> arm: fix broadcom dtree prefix

deps/sysobj_early/data/vendor.ids
Adds Union Memory for Lenovo laptops, and fixes some LG-related mismatches.
=> vendor.ids: updates

modules/benchmark.c
Fixes https://github.com/lpereira/hardinfo/issues/497
=> fix bench_value_from_str() for floats with , for decimal

hardinfo/pci_util.c, hardinfo/udisks2_util.c, includes/pci_util.h, modules/devices.c, modules/devices/storage.c
=> Try and get vendor for NVMe from PCI

hardinfo/info.c, hardinfo/usb_util.c, includes/info.h, includes/usb_util.h, modules/computer.c, modules/devices.c, modules/devices/inputdevices.c
- Added vendor / product name from usb.ids
- Added new type "audio" for ALSA devices
- Added columns Vendor tag and Type
- Fixed computer/summary output
=> Updated input devices

CMakeLists.txt, deps/sysobj_early/include/cpubits.h, deps/sysobj_early/src/cpubits.c, hardinfo/cpu_util.c
Newer version of cpubits from sysobj and a fix from @bernhardu in #503. Thanks.
=> Fix for cpubits macros

deps/sysobj_early/data/vendor.ids
- Updated Chicony and Sapphire
- Added Google and RaidSonic
=> Updated vendors.ids

hardinfo/info.c, hardinfo/util.c, includes/hardinfo.h, includes/info.h, modules/devices/firmware.c
=> firmware: switched to D-Bus

deps/sysobj_early/data/sort_vendors.pl, deps/sysobj_early/data/vendor.ids
Some vendors were lost last time, so fix the sort script and re-sort.
=> re-sort vendor.ids

deps/sysobj_early/include/util_edid.h, deps/sysobj_early/src/util_edid.c
Not a perfect fix, but moves forward.
Need to look at this more later.
Fixes #525
=> util_edid: make buildable on glib<2.52

modules/computer.c
Fixes https://github.com/lpereira/hardinfo/issues/541
=> Fix format not a string literal warning

includes/benchmark.h
The app fails to compile with GCC10.
cc @lpereira
=> Fix failed compilation

modules/devices/inputdevices.c
This PR adds BUS type label into input devices
=> devices/input: Added BUS type labels

modules/devices.c
=> devices/storage: removed leading whitespace

modules/devices/storage.c
Added more SMART Attributes keys - so they are now translatable
=> devices/storage: Added more SMART Attributes keys

po/pt.po
It still needs some work but it is something to start...
=> Add Portuguese translation
